spring:
    datasource:
        platform: postgres
        url: jdbc:postgresql://containers-us-west-202.railway.app:8014/railway
        username: omotknfghxwjrk
        password: bb7brlkpVzrGlpFCbQfH
        driverClassName: org.postgresql.Driver
        initialization-mode: always
        initialize: true
        schema: classpath:/schema-postgresql.sql


    jpa: 
        hibernate:
            ddl-auto: create-drop